Attribute VB_Name = "modGlobal"
'@Folder("TestingFramework")
Option Explicit

Public Const DEFAULT_CONSOLE_WIDTH = 800
Public Const DEFAULT_CONSOLE_HEIGHT = 350
Public Const DEFAULT_MARGIN_LEFT = 12
Public Const DEFAULT_MARGIN_TOP = 6
Public Const DEFAULT_CONSOLE_LINE_WIDTH = 762
Public Const DEFAULT_CONSOLE_LINE_HEIGHT = 14
Public Const DEFAULT_CONSOLE_FONT = "Cascadia Mono SemiLight"
Public Const DEFAULT_CONSOLE_FONTSIZE = 11
Public Const DEFAULT_CONSOLE_BACKCOLOR = CONSOLE_COLOR_BLACK
Public Const DEFAULT_CONSOLE_FONTCOLOR = CONSOLE_COLOR_WHITE

'Public Const CONSOLE_COLOR_GREEN = &HFF00&
Public Const CONSOLE_COLOR_GREEN = &H80FF80
Public Const CONSOLE_COLOR_WHITE = &HFFFFFF
Public Const CONSOLE_COLOR_YELLLOW = &HFFFF&
Public Const CONSOLE_COLOR_RED = &H8080FF
Public Const CONSOLE_COLOR_BLACK = &H0&
Public Const CONSOLE_COLOR_GREY = &HC0C0C0
Public Const CONSOLE_COLOR_DARKGREY = &HC0C0C0

Public pTestCollector As TestCollector

